---
- name: check for reboot and maybe do it 
  hosts: all 
  tasks:
     - name: Check if a reboot is needed on Ubuntu/Debian
       register: reboot_required_file
       stat: path=/var/run/reboot-required get_md5=no
 
     - name: Reboot  
       reboot:
          msg: "Reboot initiated by Ansible for kernel updates"
          connect_timeout: 5
          reboot_timeout: 300
          pre_reboot_delay: 0
          post_reboot_delay: 30
          test_command: uptime
       when: reboot_required_file.stat.exists
